version: "3.9"
services:
  db:
    container_name: entso-db
    image: timescale/timescaledb:latest-pg14
    restart: always
    environment:
      - POSTGRES_USER=entso
      - POSTGRES_PASSWORD=entso
      - POSTGRES_DB=postgres
    volumes:
      - ./data/pg:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    command: postgres -c  'timescaledb.telemetry_level=off'

  entso-dashboard:
    build: .
    container_name: entso-dashboard
    image: registry.git.fh-aachen.de/nowum-energy/software-werkzeuge/entsoe-monitor:latest
    restart: always
    environment:
      - DATABASE_URI_ENTSOE=postgresql://entso:entso@db:5432/entsoe
      - DATABASE_URI_ENTSOG=postgresql://entso:entso@db:5432/entsog
      - ENTSOE_API_KEY=XXX
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
